name: Deploy Blazor WebAssembly to GitHub Pages
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore packages
        run: dotnet restore

      - name: Publish Blazor project
        run: dotnet publish SharpFarm.csproj -c Release -o release

      - name: Build and copy Roslyn DLLs + loader.js
        run: |
          mkdir -p release/wwwroot/roslyn
          
          # Temporary project to fetch Roslyn DLLs
          dotnet new console -n TempRoslyn -o temp_roslyn
          cd temp_roslyn
          dotnet add package Microsoft.CodeAnalysis.CSharp --version 4.10.0
          dotnet add package Microsoft.CodeAnalysis.Scripting --version 4.10.0
          dotnet restore
          dotnet build -c Release
          
          # Copy Roslyn DLLs into the Blazor output
          cp bin/Release/net*/Microsoft.CodeAnalysis*.dll ../release/wwwroot/roslyn/
          
          # Add a minimal loader.js so the ScriptRunner can find it
          echo "window.CSharpWasm={runScript:async function(code,worldRef){console.log('[CSharpWasm] running:',code);return 'OK';}};" > ../release/wwwroot/roslyn/loader.js
          
          cd ..
          rm -rf temp_roslyn

          echo "Roslyn files in publish dir:"
          ls -l release/wwwroot/roslyn

      - name: Fix base href for GitHub Pages
        run: sed -i 's|<base href="/"|<base href="/SharpFarm/"|' release/wwwroot/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: release/wwwroot
          force_orphan: true
