name: Deploy Blazor WebAssembly to GitHub Pages
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore packages
        run: dotnet restore

      - name: Publish Blazor project
        run: dotnet publish SharpFarm.csproj -c Release -o release

      - name: Build and copy Roslyn DLLs + loader.js
        run: |
          mkdir -p release/wwwroot/roslyn
          
          # Temporary project for Roslyn assemblies
          dotnet new console -n TempRoslyn -o temp_roslyn
          cd temp_roslyn
          dotnet add package Microsoft.CodeAnalysis.CSharp --version 4.10.0
          dotnet add package Microsoft.CodeAnalysis.Scripting --version 4.10.0
          dotnet restore
          dotnet build -c Release

          # Copy the actual built DLLs to /wwwroot/roslyn
          FRAMEWORK=$(ls bin/Release)
          cp bin/Release/$FRAMEWORK/*.dll ../release/wwwroot/roslyn/ || true
          cp bin/Release/$FRAMEWORK/ref/*.dll ../release/wwwroot/roslyn/ || true

          # ✅ Generate loader.js (minified one-liner)
          echo "window.CSharpWasm={runScript:async function(code,worldRef){if(!window.csharpWasmReady){window.csharpWasmReady=true;}return CSharpWasm.eval(code,{world:worldRef});}};async function loadCSharpWasm(){}" > ../release/wwwroot/roslyn/loader.js

          cd ..
          rm -rf temp_roslyn

          echo "Roslyn files in publish dir:"
          ls -l release/wwwroot/roslyn

      - name: Fix base href for GitHub Pages
        run: sed -i 's|<base href="/"|<base href="/SharpFarm/"|' release/wwwroot/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: release/wwwroot
          force_orphan: true
