name: Deploy Blazor WebAssembly to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore packages
        run: dotnet restore

      - name: Publish .NET
        run: dotnet publish -c Release -o release

      - name: Copy Roslyn DLLs
        run: |
          mkdir -p release/wwwroot/roslyn
          dotnet new console -n TempRoslyn -o temp_roslyn
          cd temp_roslyn
          dotnet add package Microsoft.CodeAnalysis.CSharp --version 4.10.0
          dotnet add package Microsoft.CodeAnalysis.Scripting --version 4.10.0
          dotnet restore
          cp bin/Debug/net8.0/*.dll ../release/wwwroot/roslyn/
          cd ..
          rm -rf temp_roslyn

      - name: Change base-href
        run: |
          sed -i 's|<base href="/"|<base href="/SharpFarm/"|' release/wwwroot/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: release/wwwroot
